#name: Android CI
#
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      # Runs a single command using the runners shell
#      - name: Run a one-line script
#        run: echo Hello, world!
#      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
#    # - name: set up JDK 11
#    #   uses: actions/setup-java@v4
#    #   with:
#    #     java-version: '11'
#    #     distribution: 'temurin'
#    #     cache: gradle
#
#    # - name: Grant execute permission for gradlew
#    #   run: chmod +x gradlew
#    # - name: Build with Gradle
#    #   run: ./gradlew build
