name: CD release

on:
  push:
    branches: [ "main" ]
    tags:
      - "*"

jobs:
  Hello:
    name: Say Hello
    runs-on: ubuntu-latest

    steps:
      - name: Print job name
        run: |
          echo "JOB: github.job: ${{ github.job }}!"

      - name: Run a multiline script
        run: |
          echo "Hello, github.job: ${{ github.job }}!"
          echo "event_name: ${{ event_name }}!"

#  Build-release:
#    name: Build release apk
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Print job name
#        run: |
#          echo "JOB: github.job: ${{ github.job }}!"
#
#      - uses: actions/checkout@v4
#
#      - uses: actions/setup-java@v4
#        with:
#          java-version: 17
#          distribution: 'temurin'
#          cache: gradle
